stages:
  - name: classified request

    request:
      url: "http://127.0.0.1:5000/api/"
      method: POST
      json:
        chat: 1488
        source: "site"
        sender: "user"
        datetime: "2019-04-24T15:19:21+03:00"
        text: "привет"
      headers:
        content-type: application/json

    response:
      status_code: 200
      body:
        type: "answer"
        data:
          - text: "Здравствуйте! Какой у Вас вопрос?"
            categories: [{
                'id': 13,
                'name': "Сообщение без смысла"
            }]
